"""
Curated recurring events: firm insight programs, competitions, conferences,
fellowships, winternships. These are things that happen every year but whose
pages rarely expose machine-readable dates. The scraper re-checks each URL on
every run and pulls in concrete dates / deadlines when the page states them.

Fields
  title, host, type, tracks, url, format, location, eligibility, when, month
    type     : Insight program | Competition | Hackathon | Conference | Career fair |
               Fellowship | Winternship | Firm event
    tracks   : subset of ["Quant", "SWE", "AI/ML", "Finance"]
    format   : "Virtual" | "In person" | "Hybrid" | "Varies"
    when     : human sentence about typical timing (shown on the card)
    month    : month number of the *event* (used to place it on the calendar when
               the page gives no date); 0 = rolling / year-round
    start/end/deadline (optional): ISO dates you know for the current season
"""

CURATED = [
    # ------------------------------------------------------------ Jane Street
    dict(title="Jane Street INSIGHT", host="Jane Street", type="Insight program", tracks=["Quant", "SWE"],
         url="https://www.janestreet.com/join-jane-street/programs-and-events/insight/", format="In person", location="New York, NY",
         eligibility="Women, trans & gender-expansive undergrads (2nd/3rd year)", when="Multi-day program in January; applications open early fall", month=1),
    dict(title="Jane Street FTTP (First-year Trading & Technology Program)", host="Jane Street", type="Insight program", tracks=["Quant", "SWE"],
         url="https://www.janestreet.com/join-jane-street/programs-and-events/fttp/", format="In person", location="New York, NY",
         eligibility="First-year undergrads", when="Runs late March; applications open in the fall", month=3),
    dict(title="Jane Street SEE (Sophomore Exploration Experience)", host="Jane Street", type="Insight program", tracks=["Quant", "SWE"],
         url="https://www.janestreet.com/join-jane-street/programs-and-events/see/", format="In person", location="New York, NY",
         eligibility="First & second-year undergrads", when="Spring program; express interest year-round", month=4),
    dict(title="Jane Street WiSTEM", host="Jane Street", type="Insight program", tracks=["Quant", "SWE"],
         url="https://www.janestreet.com/join-jane-street/programs-and-events/wistem/", format="In person", location="New York, NY",
         eligibility="Women in STEM, penultimate year", when="Spring program; applications typically open in winter", month=3),
    dict(title="Jane Street Immersion Program (JSIP)", host="Jane Street", type="Fellowship", tracks=["SWE"],
         url="https://www.janestreet.com/join-jane-street/programs-and-events/jsip/", format="In person", location="New York, NY",
         eligibility="First-year undergrads from underrepresented backgrounds", when="Summer program; applications open in the fall", month=6),
    dict(title="Jane Street Electronic Trading Challenge (ETC)", host="Jane Street", type="Competition", tracks=["Quant", "SWE"],
         url="https://www.janestreet.com/join-jane-street/programs-and-events/etc/", format="In person", location="New York, NY",
         eligibility="Undergrads, teams of 3", when="Weekend competition in the spring; invite-based, express interest online", month=2),
    dict(title="Jane Street Puzzles", host="Jane Street", type="Competition", tracks=["Quant"],
         url="https://www.janestreet.com/puzzles/current-puzzle/", format="Virtual", location="Online",
         eligibility="Anyone", when="New puzzle every month; solvers listed on the site", month=0),
    dict(title="Jane Street Trading & Technology Program (TTP)", host="Jane Street", type="Insight program", tracks=["Quant", "SWE"],
         url="https://www.janestreet.com/join-jane-street/programs-and-events/", format="In person", location="New York, NY",
         eligibility="Undergrads", when="See programs page for the current season", month=0),
    # ------------------------------------------------------------ Citadel / Citadel Securities
    dict(title="Discover Citadel", host="Citadel", type="Insight program", tracks=["Quant", "SWE", "Finance"],
         url="https://www.citadel.com/careers/programs-and-events/discover-citadel/", format="In person", location="New York, NY",
         eligibility="First & second-year undergrads", when="Two-day event in the spring; applications open around November", month=3),
    dict(title="Citadel Datathon (Women's Datathon / Summer Invitational)", host="Citadel", type="Competition", tracks=["AI/ML", "Quant"],
         url="https://www.citadel.com/careers/programs-and-events/datathons/", format="Varies", location="Multiple / virtual",
         eligibility="Undergrads graduating Dec 2027 – Jun 2029", when="Several rounds a year; check page for the next one", month=0),
    dict(title="Citadel Terminal (coding competition)", host="Citadel", type="Competition", tracks=["SWE", "AI/ML"],
         url="https://www.citadel.com/careers/programs-and-events/terminal/", format="Virtual", location="Online",
         eligibility="Undergrads", when="Live tournaments through the year; register online", month=0),
    dict(title="Citadel Trading Invitational", host="Citadel", type="Competition", tracks=["Quant"],
         url="https://www.citadel.com/careers/programs-and-events/the-trading-invitational/", format="In person", location="New York, NY",
         eligibility="Undergrads", when="Invite-based; applications in the fall", month=0),
    dict(title="Citadel Fixed Income & Macro Central Bank Challenge", host="Citadel", type="Competition", tracks=["Quant", "Finance"],
         url="https://www.citadel.com/careers/programs-and-events/the-fixed-income-macro-central-bank-challenge/", format="In person", location="New York, NY",
         eligibility="Undergrads", when="Check page for the current season", month=0),
    dict(title="Citadel Conference Travel Grant (GHC, Tapia, NeurIPS…)", host="Citadel", type="Conference", tracks=["SWE", "AI/ML"],
         url="https://www.citadel.com/careers/programs-and-events/conference-travel-grant/", format="Varies", location="Varies",
         eligibility="Undergrads, PhDs, postdocs", when="Applications open a few months before each conference", month=0),
    dict(title="Citadel Securities Datathon", host="Citadel Securities", type="Competition", tracks=["AI/ML", "Quant"],
         url="https://www.citadelsecurities.com/careers/programs-and-events/datathons/", format="Varies", location="Multiple / virtual",
         eligibility="Undergrads", when="Several rounds a year", month=0),
    # ------------------------------------------------------------ SIG
    dict(title="SIG Discovery Days", host="Susquehanna (SIG)", type="Insight program", tracks=["Quant", "SWE"],
         url="https://careers.sig.com/sig-discovery-days/", format="In person", location="Bala Cynwyd, PA",
         eligibility="First & second-year undergrads", when="Held in March; applications open in the winter", month=3),
    dict(title="SIG campus events", host="Susquehanna (SIG)", type="Firm event", tracks=["Quant", "SWE"],
         url="https://careers.sig.com/events", format="Varies", location="Varies",
         eligibility="Students", when="Info sessions, trading games and workshops through the year", month=0),
    # ------------------------------------------------------------ D. E. Shaw
    dict(title="D. E. Shaw Fellowships (Latitude, Momentum, Ascend, Nexus, Discovery)", host="D. E. Shaw", type="Insight program", tracks=["Quant", "SWE", "Finance"],
         url="https://fellowships.deshaw.com/", format="In person", location="New York, NY",
         eligibility="First, second & third-year undergrads (varies by program)", when="Three-day programs in the spring and summer; applications open in the fall", month=3),
    # ------------------------------------------------------------ HRT / Virtu / IMC / Optiver / others
    dict(title="HRT Women in Trading & Technology Internship (winternship)", host="Hudson River Trading", type="Winternship", tracks=["Quant", "SWE"],
         url="https://www.hudsonrivertrading.com/student-opportunities/", format="In person", location="New York, NY",
         eligibility="Freshman & sophomore women", when="2–4 weeks in January; applications open in September", month=1),
    dict(title="Virtu Women's Winternship", host="Virtu Financial", type="Winternship", tracks=["Quant", "SWE"],
         url="https://www.virtu.com/careers/", format="In person", location="New York, NY",
         eligibility="Sophomore women", when="One week in January; applications open in September", month=1),
    dict(title="IMC Prosperity (global trading challenge)", host="IMC Trading", type="Competition", tracks=["Quant", "SWE"],
         url="https://prosperity.imc.com/", format="Virtual", location="Online",
         eligibility="University students, teams up to 5", when="Tutorial round mid-March; rounds mid-to-late April; registration opens ~February", month=4,
         start="2027-04-14", end="2027-04-30"),
    dict(title="IMC events & insight days", host="IMC Trading", type="Firm event", tracks=["Quant", "SWE"],
         url="https://www.imc.com/us/events", format="Varies", location="Chicago, IL / virtual",
         eligibility="Students", when="Posted on IMC's events page as they open", month=0),
    dict(title="Optiver events & insight days", host="Optiver", type="Firm event", tracks=["Quant", "SWE"],
         url="https://optiver.com/working-at-optiver/events/", format="Varies", location="Chicago, IL / Austin, TX / virtual",
         eligibility="Students", when="Posted on Optiver's events page as they open", month=0),
    dict(title="Flow Traders Trading Business Course", host="Flow Traders", type="Insight program", tracks=["Quant"],
         url="https://www.flowtraders.com/careers/events", format="In person", location="New York, NY",
         eligibility="Undergrads", when="Multi-day course; dates on the events page", month=0),
    dict(title="Two Sigma events & programs", host="Two Sigma", type="Firm event", tracks=["Quant", "AI/ML", "SWE"],
         url="https://www.twosigma.com/careers/", format="Varies", location="New York, NY / virtual",
         eligibility="Students", when="Info sessions and campus events through recruiting season", month=0),
    dict(title="Akuna Capital campus events", host="Akuna Capital", type="Firm event", tracks=["Quant", "SWE"],
         url="https://akunacapital.com/careers", format="Varies", location="Chicago, IL",
         eligibility="Students", when="Info sessions and trading games in the fall", month=0),
    dict(title="DRW campus events", host="DRW", type="Firm event", tracks=["Quant", "SWE"],
         url="https://drw.com/careers/campus/", format="Varies", location="Chicago, IL",
         eligibility="Students", when="Info sessions and campus visits in the fall", month=0),
    dict(title="WorldQuant International Quant Championship", host="WorldQuant", type="Competition", tracks=["Quant"],
         url="https://www.worldquant.com/international-quant-championship/", format="Virtual", location="Online",
         eligibility="University students", when="Registration in early spring; rounds run spring into summer", month=3),
    dict(title="Rotman International Trading Competition (RITC)", host="Rotman School / U of Toronto", type="Competition", tracks=["Quant"],
         url="https://ritc.rotman.utoronto.ca/", format="In person", location="Toronto, Canada",
         eligibility="University teams", when="Late February; schools register in the fall", month=2),
    dict(title="UChicago Trading Competition", host="University of Chicago", type="Competition", tracks=["Quant"],
         url="https://tradingcompetition.uchicago.edu/", format="In person", location="Chicago, IL",
         eligibility="University teams", when="Held in April; registration in the winter", month=4),
    dict(title="Bloomberg Trading Challenge", host="Bloomberg", type="Competition", tracks=["Finance", "Quant"],
         url="https://www.bloomberg.com/professional/product/bloomberg-trading-challenge/", format="Virtual", location="Online",
         eligibility="University teams", when="Fall and spring editions", month=10),
    dict(title="Bloomberg First Year Insights", host="Bloomberg", type="Insight program", tracks=["SWE", "Finance"],
         url="https://www.bloomberg.com/company/career/first-year-insights/", format="In person", location="New York, NY",
         eligibility="First-year undergrads", when="Spring program; applications open in the fall", month=3),
    dict(title="Point72 events & programs", host="Point72", type="Firm event", tracks=["Quant", "Finance"],
         url="https://www.point72.com/careers/", format="Varies", location="Stamford, CT / New York, NY",
         eligibility="Students", when="See careers page", month=0),
    # ------------------------------------------------------------ Banks
    dict(title="JPMorgan Code for Good (hackathon)", host="JPMorgan", type="Hackathon", tracks=["SWE"],
         url="https://careers.jpmorgan.com/us/en/students/programs/code-for-good", format="In person", location="Multiple US offices",
         eligibility="Undergrads", when="Fall weekends (Sep–Nov); applications open in the summer", month=10),
    dict(title="JPMorgan Career.edYOU / Sophomore Edge", host="JPMorgan", type="Insight program", tracks=["SWE", "Finance"],
         url="https://careers.jpmorgan.com/us/en/students/programs", format="Hybrid", location="New York, NY",
         eligibility="Sophomores", when="Spring programs; applications in the fall", month=3),
    dict(title="Goldman Sachs Possibilities Summits", host="Goldman Sachs", type="Insight program", tracks=["Finance", "SWE"],
         url="https://www.goldmansachs.com/careers/students/programs-and-entry-points/americas/possibilities-summits", format="In person", location="New York, NY",
         eligibility="First & second-year undergrads", when="Spring; applications open in the fall", month=3),
    dict(title="Goldman Sachs Engineering Essentials / campus events", host="Goldman Sachs", type="Firm event", tracks=["SWE"],
         url="https://www.goldmansachs.com/careers/students/programs-and-entry-points", format="Varies", location="Varies",
         eligibility="Students", when="See programs page", month=0),
    dict(title="Morgan Stanley Early Insights programs", host="Morgan Stanley", type="Insight program", tracks=["SWE", "Finance", "Quant"],
         url="https://www.morganstanley.com/careers/students-graduates/early-insights-programs", format="Varies", location="New York, NY",
         eligibility="First & second-year undergrads", when="Spring programs; applications in the fall", month=3),
    # ------------------------------------------------------------ Big tech
    dict(title="Google STEP internship (first & second years)", host="Google", type="Insight program", tracks=["SWE"],
         url="https://buildyourfuture.withgoogle.com/programs/step", format="In person", location="Multiple US offices",
         eligibility="First & second-year undergrads", when="Applications open around October", month=10),
    dict(title="Microsoft Explore program", host="Microsoft", type="Insight program", tracks=["SWE"],
         url="https://careers.microsoft.com/v2/global/en/exploremicrosoft", format="In person", location="Redmond, WA",
         eligibility="First & second-year undergrads", when="Applications open in the fall", month=10),
    dict(title="Meta University", host="Meta", type="Insight program", tracks=["SWE", "AI/ML"],
         url="https://www.metacareers.com/careerprograms/pathways/metauniversity", format="In person", location="Menlo Park, CA / New York, NY",
         eligibility="First & second-year undergrads", when="Applications open in the fall", month=10),
    dict(title="Palantir Launch", host="Palantir", type="Insight program", tracks=["SWE"],
         url="https://www.palantir.com/careers/students/launch/", format="In person", location="Denver, CO / New York, NY",
         eligibility="First & second-year undergrads", when="Spring; applications in the winter", month=3),
    dict(title="Uber Career Prep Fellowship", host="Uber", type="Fellowship", tracks=["SWE"],
         url="https://www.uber.com/us/en/careers/careerprep/", format="Virtual", location="Online",
         eligibility="First & second-year undergrads", when="Applications open in the fall", month=10),
    dict(title="Meta Hacker Cup", host="Meta", type="Competition", tracks=["SWE"],
         url="https://www.facebook.com/codingcompetitions/hacker-cup", format="Virtual", location="Online",
         eligibility="Anyone", when="Rounds September–October", month=9),
    dict(title="MIT Battlecode", host="MIT", type="Competition", tracks=["SWE", "AI/ML"],
         url="https://battlecode.org/", format="Virtual", location="Online",
         eligibility="Students", when="Runs through January; finals in February", month=1),
    dict(title="ICPC North America regionals", host="ICPC", type="Competition", tracks=["SWE"],
         url="https://icpc.global/regionals/finder", format="In person", location="Multiple US sites",
         eligibility="University teams", when="Regionals October–November; NAC in the spring", month=10),
    dict(title="William Lowell Putnam Competition", host="MAA", type="Competition", tracks=["Quant"],
         url="https://www.maa.org/math-competitions/putnam-competition", format="In person", location="Your university",
         eligibility="Undergrads", when="First Saturday in December; register through your math department", month=12),
    dict(title="Kaggle competitions", host="Kaggle", type="Competition", tracks=["AI/ML"],
         url="https://www.kaggle.com/competitions", format="Virtual", location="Online",
         eligibility="Anyone", when="Rolling — new competitions monthly", month=0),
    # ------------------------------------------------------------ Fellowships / bootcamps
    dict(title="MLH Fellowship", host="Major League Hacking", type="Fellowship", tracks=["SWE"],
         url="https://fellowship.mlh.io/", format="Virtual", location="Online",
         eligibility="Students", when="Spring, summer and fall cohorts; rolling applications", month=0),
    dict(title="CodePath Summer Internship for Tech Excellence (SITE)", host="CodePath", type="Fellowship", tracks=["SWE"],
         url="https://www.codepath.org/", format="Virtual", location="Online",
         eligibility="Sophomores", when="Applications in the winter", month=6),
    dict(title="SEO Tech Developer", host="SEO", type="Fellowship", tracks=["SWE"],
         url="https://tech.seo-usa.org/", format="Virtual", location="Online",
         eligibility="Sophomores", when="Applications open in the fall", month=6),
    dict(title="Google Summer of Code", host="Google", type="Fellowship", tracks=["SWE"],
         url="https://summerofcode.withgoogle.com/", format="Virtual", location="Online",
         eligibility="Students & beginners in open source", when="Applications in March–April", month=3),
    # ------------------------------------------------------------ Conferences & career fairs
    dict(title="Grace Hopper Celebration 2026", host="AnitaB.org", type="Conference", tracks=["SWE", "AI/ML"],
         url="https://ghc.anitab.org/", format="Hybrid", location="Anaheim, CA",
         eligibility="Everyone; student scholarships available", when="October 27–30, 2026", month=10, start="2026-10-27", end="2026-10-30"),
    dict(title="Tapia Conference 2026", host="CMD-IT", type="Conference", tracks=["SWE", "AI/ML"],
         url="https://tapiaconference.cmd-it.org/", format="In person", location="Atlanta, GA",
         eligibility="Everyone; student scholarships available", when="September 16–18, 2026", month=9, start="2026-09-16", end="2026-09-18"),
    dict(title="Rewriting the Code Career Summit", host="Rewriting the Code", type="Career fair", tracks=["SWE"],
         url="https://rewritingthecode.org/", format="Virtual", location="Online",
         eligibility="RTC members (free)", when="Fall virtual summit", month=9),
    dict(title="AfroTech Conference", host="AfroTech", type="Conference", tracks=["SWE", "AI/ML"],
         url="https://afrotech.com/conference", format="In person", location="Houston, TX",
         eligibility="Everyone", when="Early November", month=11),
    dict(title="SHPE National Convention", host="SHPE", type="Conference", tracks=["SWE"],
         url="https://shpe.org/engage/events/national-convention/", format="In person", location="Varies",
         eligibility="Everyone", when="Late October / early November", month=11),
    dict(title="NSBE Annual Convention", host="NSBE", type="Conference", tracks=["SWE"],
         url="https://convention.nsbe.org/", format="In person", location="Varies",
         eligibility="Everyone", when="March", month=3),
    dict(title="SWE Annual Conference (WE)", host="Society of Women Engineers", type="Conference", tracks=["SWE"],
         url="https://we.swe.org/", format="In person", location="Varies",
         eligibility="Everyone", when="Late October / November", month=11),
    dict(title="CMU Technical Opportunities Conference (TOC)", host="Carnegie Mellon", type="Career fair", tracks=["SWE", "AI/ML", "Quant"],
         url="https://www.cmu.edu/career/events/toc/", format="In person", location="Pittsburgh, PA",
         eligibility="CMU students", when="Mid-September", month=9),
    dict(title="YC AI Startup School", host="Y Combinator", type="Conference", tracks=["AI/ML", "SWE"],
         url="https://events.ycombinator.com/", format="In person", location="San Francisco, CA",
         eligibility="CS/ML undergrads & grad students", when="Summer; applications in the spring", month=6),
    # ------------------------------------------------------------ Flagship hackathons (MLH/Devpost also catch these)
    dict(title="TartanHacks", host="ScottyLabs (CMU)", type="Hackathon", tracks=["SWE"],
         url="https://tartanhacks.com/", format="In person", location="Pittsburgh, PA",
         eligibility="Students", when="Early February", month=2),
    dict(title="HackMIT", host="MIT", type="Hackathon", tracks=["SWE", "AI/ML"],
         url="https://hackmit.org/", format="In person", location="Cambridge, MA",
         eligibility="Undergrads; applications in the summer", when="Mid-September", month=9),
    dict(title="TreeHacks", host="Stanford", type="Hackathon", tracks=["SWE", "AI/ML"],
         url="https://www.treehacks.com/", format="In person", location="Stanford, CA",
         eligibility="Students; applications in the fall", when="February", month=2),
    dict(title="PennApps", host="UPenn", type="Hackathon", tracks=["SWE"],
         url="https://pennapps.com/", format="In person", location="Philadelphia, PA",
         eligibility="Students", when="September", month=9),
    dict(title="Cal Hacks", host="UC Berkeley", type="Hackathon", tracks=["SWE", "AI/ML"],
         url="https://calhacks.io/", format="In person", location="Berkeley, CA",
         eligibility="Students", when="October", month=10),
]
